# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-04 09:10
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='\u7b80\u5386\u5185\u5bb9'),
        ),
    ]
